grails-app/domain/spotifyweb/Track.groovy
package spotifyweb

class Track {
    String spotifyId
    String name
    String[] artists
    int durationMs
    int popularity

    static constraints = {
    }
}

grails-app/controllers/spotifyweb/TrackController.groovy
package spotifyweb

import grails.converters.JSON
import grails.validation.ValidationException
import static org.springframework.http.HttpStatus.*

class TrackController {

    TrackService trackService
    TrackRESTService trackRESTService
    String authKey

    TrackController() {
        Console.println('TrackController INIT')
    }

    static allowedMethods = [save: "POST", update: "PUT", delete: "DELETE"]

    def index(Integer max) {
        params.max = Math.min(max ?: 10, 100)
        respond trackService.list(params), model: [trackCount: trackService.count()]
    }

    def playSpotifyTrackFromPlaylist(String playlistId, String spotifyId) {
        authKey = session.getAttribute('authKey')
        def model = [success: trackRESTService.requestSpotifyPlayTrackFromPlaylist(playlistId, spotifyId, authKey)]
        render model as JSON
    }

    def playSpotifyTrack(String spotifyId) {
        authKey = session.getAttribute('authKey')
        def model = [success: trackRESTService.requestSpotifyPlayTrack(spotifyId, authKey)]
        render model as JSON
    }

    def searchSpotifyArtistsTracksAlbums(String query) {
        authKey = session.getAttribute('authKey')
        def albumsArtistsTracksList = trackRESTService.requestSpotifyArtistsTracksAlbums(query, authKey)
        if (albumsArtistsTracksList == false) {
            session.setAttribute('authKey', false)
            redirect controller: "home"
        } else {
            def model =
                    [
                            tracks : albumsArtistsTracksList.tracks,
                            artists: albumsArtistsTracksList.artists,
                            albums : albumsArtistsTracksList.albums
                    ]
            render model as JSON
        }
    }

    def getSpotifyTracksFromAlbum(String albumId) {
        authKey = session.getAttribute('authKey')
        def model = [tracks: trackRESTService.requestSpotifyGetTracksFromAlbum(albumId, authKey)]
        render model as JSON
    }

    def show(Long id) {
        respond trackService.get(id)
    }

    def create() {
        respond new Track(params)
    }

    def save(Track track) {
        if (track == null) {
            notFound()
            return
        }

        try {
            trackService.save(track)
        } catch (ValidationException e) {
            respond track.errors, view: 'create'
            return
        }

        request.withFormat {
            form multipartForm {
                flash.message = message(code: 'default.created.message', args: [message(code: 'track.label', default: 'Track'), track.id])
                redirect track
            }
            '*' { respond track, [status: CREATED] }
        }
    }

    def edit(Long id) {
        respond trackService.get(id)
    }

    def update(Track track) {
        if (track == null) {
            notFound()
            return
        }

        try {
            trackService.save(track)
        } catch (ValidationException e) {
            respond track.errors, view: 'edit'
            return
        }

        request.withFormat {
            form multipartForm {
                flash.message = message(code: 'default.updated.message', args: [message(code: 'track.label', default: 'Track'), track.id])
                redirect track
            }
            '*' { respond track, [status: OK] }
        }
    }

    def delete(Long id) {
        if (id == null) {
            notFound()
            return
        }

        trackService.delete(id)

        request.withFormat {
            form multipartForm {
                flash.message = message(code: 'default.deleted.message', args: [message(code: 'track.label', default: 'Track'), id])
                redirect action: "index", method: "GET"
            }
            '*' { render status: NO_CONTENT }
        }
    }

    protected void notFound() {
        request.withFormat {
            form multipartForm {
                flash.message = message(code: 'default.not.found.message', args: [message(code: 'track.label', default: 'Track'), params.id])
                redirect action: "index", method: "GET"
            }
            '*' { render status: NOT_FOUND }
        }
    }
}

grails-app/views/track/create.gsp
<!DOCTYPE html>
<html>
    <head>
        <meta name="layout" content="main" />
        <g:set var="entityName" value="${message(code: 'track.label', default: 'Track')}" />
        <title><g:message code="default.create.label" args="[entityName]" /></title>
    </head>
    <body>
        <a href="#create-track" class="skip" tabindex="-1"><g:message code="default.link.skip.label" default="Skip to content&hellip;"/></a>
        <div class="nav" role="navigation">
            <ul>
                <li><a class="home" href="${createLink(uri: '/')}"><g:message code="default.home.label"/></a></li>
                <li><g:link class="list" action="index"><g:message code="default.list.label" args="[entityName]" /></g:link></li>
            </ul>
        </div>
        <div id="create-track" class="content scaffold-create" role="main">
            <h1><g:message code="default.create.label" args="[entityName]" /></h1>
            <g:if test="${flash.message}">
            <div class="message" role="status">${flash.message}</div>
            </g:if>
            <g:hasErrors bean="${this.track}">
            <ul class="errors" role="alert">
                <g:eachError bean="${this.track}" var="error">
                <li <g:if test="${error in org.springframework.validation.FieldError}">data-field-id="${error.field}"</g:if>><g:message error="${error}"/></li>
                </g:eachError>
            </ul>
            </g:hasErrors>
            <g:form resource="${this.track}" method="POST">
                <fieldset class="form">
                    <f:all bean="track"/>
                </fieldset>
                <fieldset class="buttons">
                    <g:submitButton name="create" class="save" value="${message(code: 'default.button.create.label', default: 'Create')}" />
                </fieldset>
            </g:form>
        </div>
    </body>
</html>

grails-app/views/track/edit.gsp
<!DOCTYPE html>
<html>
    <head>
        <meta name="layout" content="main" />
        <g:set var="entityName" value="${message(code: 'track.label', default: 'Track')}" />
        <title><g:message code="default.edit.label" args="[entityName]" /></title>
    </head>
    <body>
        <a href="#edit-track" class="skip" tabindex="-1"><g:message code="default.link.skip.label" default="Skip to content&hellip;"/></a>
        <div class="nav" role="navigation">
            <ul>
                <li><a class="home" href="${createLink(uri: '/')}"><g:message code="default.home.label"/></a></li>
                <li><g:link class="list" action="index"><g:message code="default.list.label" args="[entityName]" /></g:link></li>
                <li><g:link class="create" action="create"><g:message code="default.new.label" args="[entityName]" /></g:link></li>
            </ul>
        </div>
        <div id="edit-track" class="content scaffold-edit" role="main">
            <h1><g:message code="default.edit.label" args="[entityName]" /></h1>
            <g:if test="${flash.message}">
            <div class="message" role="status">${flash.message}</div>
            </g:if>
            <g:hasErrors bean="${this.track}">
            <ul class="errors" role="alert">
                <g:eachError bean="${this.track}" var="error">
                <li <g:if test="${error in org.springframework.validation.FieldError}">data-field-id="${error.field}"</g:if>><g:message error="${error}"/></li>
                </g:eachError>
            </ul>
            </g:hasErrors>
            <g:form resource="${this.track}" method="PUT">
                <g:hiddenField name="version" value="${this.track?.version}" />
                <fieldset class="form">
                    <f:all bean="track"/>
                </fieldset>
                <fieldset class="buttons">
                    <input class="save" type="submit" value="${message(code: 'default.button.update.label', default: 'Update')}" />
                </fieldset>
            </g:form>
        </div>
    </body>
</html>

grails-app/views/track/index.gsp
<!DOCTYPE html>
<html>
    <head>
        <meta name="layout" content="main" />
        <g:set var="entityName" value="${message(code: 'track.label', default: 'Track')}" />
        <title><g:message code="default.list.label" args="[entityName]" /></title>
    </head>
    <body>
        <a href="#list-track" class="skip" tabindex="-1"><g:message code="default.link.skip.label" default="Skip to content&hellip;"/></a>
        <div class="nav" role="navigation">
            <ul>
                <li><a class="home" href="${createLink(uri: '/')}"><g:message code="default.home.label"/></a></li>
                <li><g:link class="create" action="create"><g:message code="default.new.label" args="[entityName]" /></g:link></li>
            </ul>
        </div>
        <div id="list-track" class="content scaffold-list" role="main">
            <h1><g:message code="default.list.label" args="[entityName]" /></h1>
            <g:if test="${flash.message}">
                <div class="message" role="status">${flash.message}</div>
            </g:if>
            <f:table collection="${trackList}" />

            <div class="pagination">
                <g:paginate total="${trackCount ?: 0}" />
            </div>
        </div>
    </body>
</html>

grails-app/views/track/show.gsp
<!DOCTYPE html>
<html>
    <head>
        <meta name="layout" content="main" />
        <g:set var="entityName" value="${message(code: 'track.label', default: 'Track')}" />
        <title><g:message code="default.show.label" args="[entityName]" /></title>
    </head>
    <body>
        <a href="#show-track" class="skip" tabindex="-1"><g:message code="default.link.skip.label" default="Skip to content&hellip;"/></a>
        <div class="nav" role="navigation">
            <ul>
                <li><a class="home" href="${createLink(uri: '/')}"><g:message code="default.home.label"/></a></li>
                <li><g:link class="list" action="index"><g:message code="default.list.label" args="[entityName]" /></g:link></li>
                <li><g:link class="create" action="create"><g:message code="default.new.label" args="[entityName]" /></g:link></li>
            </ul>
        </div>
        <div id="show-track" class="content scaffold-show" role="main">
            <h1><g:message code="default.show.label" args="[entityName]" /></h1>
            <g:if test="${flash.message}">
            <div class="message" role="status">${flash.message}</div>
            </g:if>
            <f:display bean="track" />
            <g:form resource="${this.track}" method="DELETE">
                <fieldset class="buttons">
                    <g:link class="edit" action="edit" resource="${this.track}"><g:message code="default.button.edit.label" default="Edit" /></g:link>
                    <input class="delete" type="submit" value="${message(code: 'default.button.delete.label', default: 'Delete')}" onclick="return confirm('${message(code: 'default.button.delete.confirm.message', default: 'Are you sure?')}');" />
                </fieldset>
            </g:form>
        </div>
    </body>
</html>